### ISSUE TITLE
一些建议和bug

### ISSUE THREAD

**Issue by NathanDai** [bin64/Clash-Dash#7]
bug:
+ 更新版本最好能保留原数据 已经升级两次每次数据都丢了

建议:
+ Clash控制器 连接面版 最好可以选择连接的设备 (可以做成默认全部 tab打开选择设备)
![image](https://github.com/user-attachments/assets/5c106f2a-ebb2-4d51-b3d4-ff2708f2dd8c)
+ OpenWRT 控制器 连不上 提示密码错误
> OpenWrt R24.03.20-D (2024-03-23) / LuCI Master (git-24.071.74519-c79d23b)
> OpenWrt R22.11.11 (2022-11-24) / LuCI Master (git-22.327.32954-9a257eb)

**Comment by bin64** [comment]
你好，关于数据保存的问题，因为一开始设计的比较简单，更新有时候会涉及到变量名称的变化，所以会导致已保存的服务器信息丢失。我会尽量避免对已有的数据进行改动。

- Clash控制器对设备的过滤我会尽快加上。

- 关于 OpenWRT 提示密码错误的问题，我这里安装了一个 OpenWrt 03.29.2024 的版本（抱歉暂时没找到你的那个版本）。麻烦你使用下面这个命令：

`curl -X "POST" "http://192.168.110.46/cgi-bin/luci/rpc/auth" 
     -H 'Content-Type: application/json' 
     -d $'{
  "id": 1,
  "method": "login",
  "params": [
    "root",
    "password"
  ]
}'`

把 `192.168.110.46` 替换为你自己的 OpenWRT 地址、`root` 和 `password` 改为你自己的账号密码后执行，请问这个的返回内容是什么呢？

**Comment by NathanDai** [comment]
> 你好，关于数据保存的问题，因为一开始设计的比较简单，更新有时候会涉及到变量名称的变化，所以会导致已保存的服务器信息丢失。我会尽量避免对已有的数据进行改动。
> 
> * Clash控制器对设备的过滤我会尽快加上。
> * 关于 OpenWRT 提示密码错误的问题，我这里安装了一个 OpenWrt 03.29.2024 的版本（抱歉暂时没找到你的那个版本），测试没有问题。所以麻烦你使用下面这个命令：
> 
> `curl -X "POST" "http://192.168.110.46/cgi-bin/luci/rpc/auth" -H 'Content-Type: application/json' -d $'{ "id": 1, "method": "login", "params": [ "root", "password" ] }'`
> 
> 把 `192.168.110.46` 替换为你自己的 OpenWRT 地址、`root` 和 `password` 改为你自己的账号密码后执行，请问这个的返回内容是什么呢？

正确密码
{"id":1,"result":"xxxxxx","error":null}

错误密码
{"id":1,"result":null,"error":null}

**Comment by bin64** [comment]
你现在使用的 v1.2.1 的版本么？登录的时候提示什么呢？

**Comment by NathanDai** [comment]
![C46E4303-1AB8-48D2-BC5D-34CC4B5E51A0_4_5005_c](https://github.com/user-attachments/assets/9e9b7e79-2176-4df1-b190-0a841dd00e6f)

**Comment by bin64** [comment]
你好，你这个提示就是账号不对的时候无法获取到 token 的提示。

你的用户名是什么呢？一般来说 OpenWRT 的应该是 root 吧？我看你下面输入的用户名是 19 开头的。

你可以尝试使用 root 来登录试试（请先更新到商店 v1.2.2 版本）

**Comment by NathanDai** [comment]
> 你好，你这个提示就是账号不对的时候无法获取到 token 的提示。
> 
> 你的用户名是什么呢？一般来说 OpenWRT 的应该是 root 吧？我看你下面输入的用户名是 19 开头的。
> 
> 你可以尝试使用 root 来登录试试（请先更新到商店 v1.2.2 版本）

我就是用root登录的 使用的是最近App版本

**Comment by bin64** [comment]
哈喽，我看到你上面写的用户名是 19 开头的，使用 root 登录也是同样的提示么？

如果可以的话你可以 TG 联系我么？我这里没能复现你那边的问题。我的 TG 是：https://t.me/yinigo 谢谢

**Comment by bin64** [comment]
你好，你的 TG 似乎不能使用了，请更新 v1.2.4 的版本看看能不能使用 OpenWRT 方式登录呢，谢谢。

**Comment by NathanDai** [comment]
> 你好，你的 TG 似乎不能使用了，请更新 v1.2.4 的版本看看能不能使用 OpenWRT 方式登录呢，谢谢。

不好意思 那天发了你一张截图然后号被封掉了
稍等一下 我重新注册一下

**Comment by bin64** [comment]
你好，我可能知道是什么问题了。OpenWRT 在不同版本中的 Cookie 验证逻辑不一样，有的验证 `sysauth`， 有的验证 `sysauth_http`，我安装的版本都验证的 `sysauth_http`，导致获取到的 Token 在验证 `sysauth` 的 OpenWRT 版本中无法使用。

我已经提交了 v1.2.5 用来修正这个问题。你可以：
`curl -O https://raw.githubusercontent.com/bin64/Clash-Dash/refs/heads/main/Debug/get_openclash_status.sh && chmod +x get_openclash_status.sh && ./get_openclash_status.sh`

这个脚本验证一下。

**Comment by bin64** [comment]
OpenWRT 登录问题在 v1.2.6 版本已修复
