### ISSUE TITLE
延迟测试结果不能即时刷新

### ISSUE THREAD

**Issue by vialib** [bin64/Clash-Dash#8]
点击延迟测试后，只会刷新代理组概览里的延迟，展开的节点列表不会即时刷新结果![image](https://github.com/user-attachments/assets/a5bc7c17-9656-4b4e-8503-825effcf85b7)

**Comment by bin64** [comment]
你好，谢谢你提出来这个问题，这个问题 TG 群里也有人在反馈。

具体的原因是代理组依赖的问题没有考虑到（即代理组 A 的代理节点为另一个代理组 B），在这种情况下测速的时候使用 API /group/XXX/delay 不会对被依赖的代理组进行延迟检测，导致延迟的信息显示不同步。

我在本地的版本已经修复这个问题，因为还在调整 UI，所以应该会在 1.2.7 这个版本更新解决，欢迎关注👏。

**Comment by bin64** [comment]
已提交 v1.2.7 修复，商店版待审核
